with open('/Users/rodrigocasale/Documents/proyects/gba_dev/butano-18.9.0/games/guitar-hero-advance/audio/beat_it.xm', 'rb') as f:
    data = f.read(80)
    id_text   = data[0:17].decode('ascii', errors='replace')
    mod_name  = data[17:37].decode('ascii', errors='replace').rstrip()
    tracker   = data[38:58].decode('ascii', errors='replace').rstrip()
    version   = int.from_bytes(data[58:60], 'little')
    song_len  = int.from_bytes(data[64:66], 'little')
    channels  = int.from_bytes(data[68:70], 'little')
    patterns  = int.from_bytes(data[70:72], 'little')
    tempo     = int.from_bytes(data[76:78], 'little')
    bpm       = int.from_bytes(data[78:80], 'little')
    print(f'ID:       {id_text}')
    print(f'Name:     {mod_name}')
    print(f'Tracker:  {tracker}')
    print(f'Version:  0x{version:04X}')
    print(f'Length:   {song_len}')
    print(f'Channels: {channels}')
    print(f'Patterns: {patterns}')
    print(f'Tempo:    {tempo}  (ticks per row)')
    print(f'BPM:      {bpm}')